# @package annotation
detector_model: google/owlvit-base-patch32
sam_model: mobile_sam.pt
conf: 0.015
max_detections: 20
classes:
  - traffic cone
  - cardboard box
  - box
  - debris
  - animal
  - dog
  - deer
  - pothole
  - road
  - car
  - person
