
# diffusion_config is only required when training a new model from scratch
diffusion_config:
  d_layers: [512, 512]
  dropout: 0.0
  num_timesteps: 2
  model_type: mlp
  iterations: 2
  batch_size: 4
  lr: 0.0006
  gaussian_loss_type: mse
  weight_decay: 1e-05
  scheduler: cosine

sample_scale: 0.2 # Used to define the number of sampled samples based on the train data size.

# No need to change these for single table settings. These are used for multi-table settings.
sampling_config:
    batch_size: 1
    classifier_scale: 1.0

matching_config:
    num_matching_clusters: 1
    matching_batch_size: 1000
    unique_matching: True
    no_matching: False