"""Utilities for generating text synthetic data."""

from aieng.syn_data.text.clients import (
    LLMClient,
    LLMSettings,
    OpenAICompatibleClient,
    create_judge_client,
    create_teacher_client,
)
from aieng.syn_data.text.config import (
    BASELINE_PREDICTIONS_PATH,
    BASELINE_SCORES_PATH,
    COMPARISON_REPORT_PATH,
    DATA_DIR,
    DEFAULT_DOMAIN,
    DEFAULT_JUDGE_THRESHOLD,
    DEFAULT_SYNTHETIC_TARGET_SIZE,
    DEFAULT_TEST_PARAS_PER_DOC,
    DOCUMENTS_DIR,
    FAILURE_MODE_GUIDANCE,
    FINANCE_DOCUMENTS,
    FINETUNED_PREDICTIONS_PATH,
    PARAGRAPHS_PATH,
    RESULTS_DIR,
    SYNTHETIC_FILTERED_PATH,
    SYNTHETIC_RAW_PATH,
    SYNTHETIC_TRAIN_PATH,
    TEST_SET_PATH,
)
from aieng.syn_data.text.datasets import (
    download_document,
    download_url,
    list_domain_documents,
    load_paragraphs_from_text_files,
)
from aieng.syn_data.text.documents import (
    assign_test_train_split,
    chunk_text_into_paragraphs,
    load_document_text,
    make_paragraph_id,
    paragraphs_from_document,
    sample_test_paragraphs,
)
from aieng.syn_data.text.evaluation import (
    build_eval_prompt,
    compare_summaries,
    run_inference,
    summarize_by_failure_mode,
    summarize_judge_scores,
)
from aieng.syn_data.text.generation import (
    few_shot_generate,
    one_shot_generate,
    topic_controlled_generate,
    zero_shot_generate,
)
from aieng.syn_data.text.io import (
    ensure_parent,
    iter_jsonl,
    load_typed_jsonl,
    read_json,
    read_jsonl,
    save_typed_jsonl,
    write_json,
    write_jsonl,
)
from aieng.syn_data.text.judge import (
    build_absolute_judge_prompt,
    build_pairwise_judge_prompt,
    judge_response,
    judge_synthetic_sample,
    parse_judge_score,
)
from aieng.syn_data.text.paths import (
    find_repo_root,
    load_implementation_dotenv,
    use_repo_root,
)
from aieng.syn_data.text.pipeline import (
    build_paragraph_splits,
    compare_generation_strategies,
    effective_synthetic_target,
    filter_with_judge,
    generate_grounded_training_corpus,
    generate_raw_synthetic_corpus,
    generate_test_qa_batch,
    save_baseline_results,
    score_predictions,
)
from aieng.syn_data.text.quality import (
    apply_heuristic_filters,
    summarize_heuristic_rejections,
)
from aieng.syn_data.text.rag import (
    generate_grounded_qa,
    grounding_overlap_score,
    retrieve_paragraphs,
)
from aieng.syn_data.text.schemas import (
    DocumentRole,
    DocumentSpec,
    FailureMode,
    GenerationStrategy,
    JudgeScore,
    Paragraph,
    ParagraphSplit,
    QASample,
)
from aieng.syn_data.text.sft import (
    PeftInferenceClient,
    build_sft_dataset,
    qa_samples_to_messages,
    train_lora_sft,
)
from aieng.syn_data.text.small_model import create_small_model_client


__all__ = [
    "BASELINE_PREDICTIONS_PATH",
    "BASELINE_SCORES_PATH",
    "COMPARISON_REPORT_PATH",
    "DATA_DIR",
    "DEFAULT_DOMAIN",
    "DEFAULT_JUDGE_THRESHOLD",
    "DEFAULT_SYNTHETIC_TARGET_SIZE",
    "DEFAULT_TEST_PARAS_PER_DOC",
    "DOCUMENTS_DIR",
    "DocumentRole",
    "DocumentSpec",
    "FAILURE_MODE_GUIDANCE",
    "FINANCE_DOCUMENTS",
    "FINETUNED_PREDICTIONS_PATH",
    "FailureMode",
    "GenerationStrategy",
    "JudgeScore",
    "LLMClient",
    "LLMSettings",
    "OpenAICompatibleClient",
    "PARAGRAPHS_PATH",
    "Paragraph",
    "ParagraphSplit",
    "QASample",
    "RESULTS_DIR",
    "SYNTHETIC_FILTERED_PATH",
    "SYNTHETIC_RAW_PATH",
    "SYNTHETIC_TRAIN_PATH",
    "TEST_SET_PATH",
    "PeftInferenceClient",
    "apply_heuristic_filters",
    "summarize_heuristic_rejections",
    "assign_test_train_split",
    "build_paragraph_splits",
    "build_sft_dataset",
    "build_absolute_judge_prompt",
    "build_eval_prompt",
    "build_pairwise_judge_prompt",
    "chunk_text_into_paragraphs",
    "compare_generation_strategies",
    "compare_summaries",
    "create_judge_client",
    "create_small_model_client",
    "create_teacher_client",
    "download_document",
    "download_url",
    "effective_synthetic_target",
    "ensure_parent",
    "filter_with_judge",
    "find_repo_root",
    "few_shot_generate",
    "generate_grounded_qa",
    "generate_grounded_training_corpus",
    "generate_raw_synthetic_corpus",
    "generate_test_qa_batch",
    "grounding_overlap_score",
    "iter_jsonl",
    "judge_response",
    "judge_synthetic_sample",
    "list_domain_documents",
    "load_document_text",
    "load_implementation_dotenv",
    "load_paragraphs_from_text_files",
    "load_typed_jsonl",
    "make_paragraph_id",
    "one_shot_generate",
    "paragraphs_from_document",
    "parse_judge_score",
    "qa_samples_to_messages",
    "read_json",
    "read_jsonl",
    "retrieve_paragraphs",
    "run_inference",
    "save_baseline_results",
    "score_predictions",
    "sample_test_paragraphs",
    "save_typed_jsonl",
    "summarize_by_failure_mode",
    "summarize_judge_scores",
    "topic_controlled_generate",
    "train_lora_sft",
    "use_repo_root",
    "write_json",
    "write_jsonl",
    "zero_shot_generate",
]
