# Synthesizing config
sampling_config:
    sample_scale: 0.25 # Ratio of the number of synthesized rows compared to the number of original rows
    batch_size: 10
    classifier_scale: 1.0

matching_config:
    num_matching_clusters: 1
    matching_batch_size: 10
    unique_matching: True
    no_matching: False