name: publish package
permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libssl-dev
      - uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          # Install a specific version of uv.
          version: "0.9.11"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          cd aieng-synthetic-data
          uv venv .venv
          source .venv/bin/activate
          uv sync --all-extras --dev

      - name: Build package
        run: cd aieng-synthetic-data && source .venv/bin/activate && uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247
        with:
          packages-dir: dist/
